const SUPABASE_URL="PASTE_YOUR_SUPABASE_PROJECT_URL_HERE";const SUPABASE_PUBLISHABLE_KEY="PASTE_YOUR_SUPABASE_PUBLISHABLE_KEY_HERE";const db=supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);const $=id=>document.getElementById(id);let user=null,profile=null,mode="login";
const esc=s=>(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function go(p){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$(p).classList.add("active");if(p==="home")feed();if(p==="categories")cats();if(p==="profile")myProfile();if(p==="admin")admin();scrollTo(0,0)}
document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>go(b.dataset.page));
function authOpen(m){mode=m;$("authModal").classList.remove("hide");$("usernameWrap").classList.toggle("hide",m!=="register");$("authSubmit").textContent=m==="register"?"Kayıt Ol":"Giriş Yap";$("tabLogin").classList.toggle("active",m==="login");$("tabRegister").classList.toggle("active",m==="register");$("authMessage").textContent=""}
$("loginBtn").onclick=()=>authOpen("login");$("registerBtn").onclick=()=>authOpen("register");$("closeAuth").onclick=()=>$("authModal").classList.add("hide");$("tabLogin").onclick=()=>authOpen("login");$("tabRegister").onclick=()=>authOpen("register");
$("authForm").onsubmit=async e=>{e.preventDefault();try{let email=$("authEmail").value.trim(),password=$("authPassword").value;if(mode==="register"){let u=$("authUsername").value.trim().toLowerCase();if(!/^[a-z0-9_.-]{3,30}$/.test(u))throw Error("Kullanıcı adı geçersiz.");let r=await db.auth.signUp({email,password,options:{data:{username:u}}});if(r.error)throw r.error;if(r.data.user)await db.from("profiles").upsert({id:r.data.user.id,username:u});$("authMessage").textContent="Kayıt başarılı. E-postanı doğrula."}else{let r=await db.auth.signInWithPassword({email,password});if(r.error)throw r.error;$("authModal").classList.add("hide")}}catch(x){$("authMessage").textContent=x.message}};
async function refresh(){let r=await db.auth.getSession();user=r.data.session?.user||null;profile=null;if(user){let r2=await db.from("profiles").select("*").eq("id",user.id).maybeSingle();profile=r2.data}$("loginBtn").classList.toggle("hide",!!user);$("registerBtn").classList.toggle("hide",!!user);$("logoutBtn").classList.toggle("hide",!user);$("adminNav").classList.toggle("hide",!["admin","moderator"].includes(profile?.role))}
$("logoutBtn").onclick=async()=>{await db.auth.signOut();refresh();go("home")};db.auth.onAuthStateChange(()=>setTimeout(refresh,0));
async function cats(){let r=await db.from("categories").select("*").order("name");$("categoryGrid").innerHTML=(r.data||[]).map(c=>`<button class="cat" data-cat="${c.id}">${esc(c.name)}</button>`).join("");document.querySelectorAll("[data-cat]").forEach(b=>b.onclick=()=>catVideos(b.dataset.cat))}
async function catVideos(id){let r=await db.from("videos").select("*,profiles(username),categories(name)").eq("category_id",id).eq("status","approved").order("created_at",{ascending:false});$("categoryVideos").innerHTML=(r.data||[]).map(card).join("")||'<div class="panel">Bu kategoride henüz video yok.</div>'}
function card(v){return `<article class="card"><video src="${esc(v.video_url)}" controls playsinline preload="metadata"></video><div class="pad"><h3>${esc(v.title)}</h3><p>@${esc(v.profiles?.username||"kullanıcı")} · ${esc(v.categories?.name||"")}</p><span class="status">${esc(v.status)}</span></div></article>`}
function short(v){return `<article class="card"><video src="${esc(v.video_url)}" controls playsinline loop preload="metadata"></video><div class="pad"><h3>${esc(v.title)}</h3><p>@${esc(v.profiles?.username||"kullanıcı")} · ${esc(v.categories?.name||"")}</p><div class="actions"><button class="action like" data-id="${v.id}">♡ Beğen</button></div></div></article>`}
async function feed(){let r=await db.from("videos").select("*,profiles(username),categories(name)").eq("status","approved").order("created_at",{ascending:false}).limit(40);$("feedStatus").textContent=`${r.data?.length||0} video`;$("shortsFeed").innerHTML=(r.data||[]).map(short).join("")||'<div class="panel">Henüz yayınlanmış video yok.</div>';document.querySelectorAll("#shortsFeed video").forEach(v=>{let io=new IntersectionObserver(es=>es.forEach(x=>x.isIntersecting?v.play().catch(()=>{}):v.pause()),{threshold:.65});io.observe(v)})}
document.addEventListener("click",async e=>{let b=e.target.closest(".like");if(!b)return;if(!user){authOpen("login");return}let r=await db.from("likes").select("*").eq("user_id",user.id).eq("video_id",b.dataset.id).maybeSingle();if(r.data)await db.from("likes").delete().eq("user_id",user.id).eq("video_id",b.dataset.id);else await db.from("likes").insert({user_id:user.id,video_id:b.dataset.id});b.textContent=r.data?"♡ Beğen":"♥ Beğen"});
$("videoFile").onchange=()=>{let f=$("videoFile").files[0];if(!f)return;if(f.size>100*1024*1024){$("uploadMessage").textContent="Maksimum 100 MB.";return}$("uploadPreview").src=URL.createObjectURL(f);$("uploadPreview").classList.remove("hide")};
async function loadCatSelect(){let r=await db.from("categories").select("id,name").order("name");$("videoCategory").innerHTML=(r.data||[]).map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join("")}
$("uploadForm").onsubmit=async e=>{e.preventDefault();if(!user){authOpen("login");return}let f=$("videoFile").files[0];try{if(!f||f.size>100*1024*1024)throw Error("Video 100 MB'dan küçük olmalı.");if(!$("safeContent").checked)throw Error("+18 olmadığını onaylamalısın.");let ext=(f.name.split(".").pop()||"mp4").toLowerCase(),path=`${user.id}/${crypto.randomUUID()}.${ext}`;let u=await db.storage.from("videos").upload(path,f,{contentType:f.type||"video/mp4"});if(u.error)throw u.error;let url=db.storage.from("videos").getPublicUrl(path).data.publicUrl;let v=await db.from("videos").insert({user_id:user.id,title:$("videoTitle").value.trim(),description:$("videoDescription").value.trim(),category_id:$("videoCategory").value,video_url:url,status:"pending"});if(v.error)throw v.error;$("uploadMessage").textContent="Video yüklendi, admin onayı bekliyor.";$("uploadForm").reset();$("uploadPreview").classList.add("hide")}catch(x){$("uploadMessage").textContent=x.message}};
async function myProfile(){if(!user){$("profileBox").innerHTML='<div class="panel">Profil için giriş yapmalısın.</div>';return}let r=await db.from("profiles").select("*").eq("id",user.id).single();profile=r.data;$("profileBox").innerHTML=`<h2>@${esc(profile?.username||"")}</h2><p class="muted">${esc(profile?.bio||"RAINMAN SHORTS kullanıcısı")}</p><p>Rol: ${esc(profile?.role||"user")}</p>`;let v=await db.from("videos").select("*,categories(name)").eq("user_id",user.id).order("created_at",{ascending:false});$("myVideos").innerHTML=(v.data||[]).map(card).join("")||'<div class="panel">Henüz video yok.</div>'}
async function admin(){if(!["admin","moderator"].includes(profile?.role)){go("home");return}let r=await db.from("videos").select("*,profiles(username),categories(name)").eq("status","pending").order("created_at");$("adminVideos").innerHTML=(r.data||[]).map(v=>`<article class="card"><video src="${esc(v.video_url)}" controls playsinline></video><div class="pad"><h3>${esc(v.title)}</h3><p>@${esc(v.profiles?.username||"")}</p><div class="actions"><button class="action decision" data-id="${v.id}" data-status="approved">✓ Onayla</button><button class="action decision" data-id="${v.id}" data-status="rejected">✕ Reddet</button></div></div></article>`).join("")||'<div class="panel">Onay bekleyen video yok.</div>'}
document.addEventListener("click",async e=>{let b=e.target.closest(".decision");if(!b)return;let r=await db.from("videos").update({status:b.dataset.status}).eq("id",b.dataset.id);if(r.error)alert(r.error.message);else admin()});
(async()=>{await refresh();await loadCatSelect();await feed()})();