const categories=["Tümü","Oyun","Komedi","Müzik","Film & Dizi","Spor","Hayvanlar","Teknoloji","Eğitim","Sanat","Yemek","Gezi","Otomobil","Yaşam","Eğlence"];
let videos=JSON.parse(localStorage.getItem("rs_videos")||"null")||[
{id:1,title:"Gece sürüşü 🌙",user:"@rainman",cat:"Gezi",likes:128,views:2100,color:1},
{id:2,title:"Bu hamle inanılmaz!",user:"@player01",cat:"Oyun",likes:540,views:8900,color:2},
{id:3,title:"Günün müzik keşfi 🎵",user:"@musicfan",cat:"Müzik",likes:312,views:4300,color:3},
{id:4,title:"Komik anlar 😂",user:"@funny",cat:"Komedi",likes:88,views:1200,color:4}
];
let users=JSON.parse(localStorage.getItem("rs_users")||"null")||[{name:"Admin",email:"admin@rainmanshorts.com",pass:"admin123",role:"admin"}];
let current=JSON.parse(localStorage.getItem("rs_current")||"null"); let selectedCat="Tümü";

const $=s=>document.querySelector(s);
function save(){localStorage.setItem("rs_videos",JSON.stringify(videos));localStorage.setItem("rs_users",JSON.stringify(users));localStorage.setItem("rs_current",JSON.stringify(current))}
function openModal(html){$("#modalContent").innerHTML=html;$("#modal").classList.remove("hidden")}
function closeModal(){$("#modal").classList.add("hidden")}
function loginForm(){openModal(`<h2>RAINMAN SHORTS</h2><div class="tabs"><button class="on">Giriş</button><button onclick="registerForm()">Kayıt Ol</button></div><form class="form" onsubmit="login(event)"><label>E-posta</label><input id="email" type="email" required><label>Şifre</label><input id="pass" type="password" required><button class="primary" style="width:100%">Giriş Yap</button></form>`)}
function registerForm(){openModal(`<h2>Hesap Oluştur</h2><form class="form" onsubmit="register(event)"><label>Kullanıcı adı</label><input id="name" required><label>E-posta</label><input id="email" type="email" required><label>Şifre</label><input id="pass" type="password" minlength="6" required><p class="muted">Kayıt olarak +18, pornografik veya yasa dışı içerik yüklemeyeceğini kabul edersin.</p><button class="primary" style="width:100%">Kayıt Ol</button></form>`)}
function login(e){e.preventDefault();let u=users.find(x=>x.email==$("#email").value&&x.pass==$("#pass").value);if(!u)return alert("E-posta veya şifre hatalı.");current=u;save();closeModal();render()}
function register(e){e.preventDefault();let email=$("#email").value;if(users.some(x=>x.email==email))return alert("Bu e-posta zaten kayıtlı.");let u={name:$("#name").value,email,pass:$("#pass").value,role:"user"};users.push(u);current=u;save();closeModal();render()}
$("#authBtn").onclick=()=>current?logout():loginForm();
function logout(){current=null;save();render()}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>page(b.dataset.page));
function page(p){render(p)}
function render(p="home"){if(p==="home")home();if(p==="explore")explore();if(p==="upload")upload();if(p==="profile")profile();if(p==="admin")admin()}
function categoryBar(){return `<div class="chips">${categories.map(c=>`<button class="chip ${c===selectedCat?'active':''}" onclick="selectedCat='${c}';render('explore')">${c}</button>`).join("")}</div>`}
function shortCard(v){return `<article class="short"><div class="poster" style="background:linear-gradient(150deg,hsl(${v.color*70},65%,35%),#090a0e)"><div style="font-size:80px;opacity:.35">▶</div></div><div class="overlay"><div class="info"><b>${v.user}</b><h3>${esc(v.title)}</h3><p>#${v.cat} · ${v.views.toLocaleString()} izlenme</p></div><div class="actions"><button class="act" onclick="like(${v.id})">❤️<small>${v.likes}</small></button><button class="act" onclick="alert('Yorum sistemi ilk sürümde demo olarak hazır.')">💬</button><button class="act" onclick="shareVideo(${v.id})">↗</button><button class="act" onclick="alert('İçerik bildirildi. Admin incelemesine gönderilecek.')">⚑</button></div></div></article>`}
function home(){let list=videos.slice(0,6);$("#content").innerHTML=`<section class="hero"><h1>Shorts dünyasına hoş geldin.</h1><p>RAINMAN SHORTS — keşfet, paylaş, eğlen.</p></section>${categoryBar()}<div class="feed">${list.map(shortCard).join("")}</div>`;observe()}
function explore(){let list=selectedCat==="Tümü"?videos:videos.filter(v=>v.cat===selectedCat);$("#content").innerHTML=`<section class="hero"><h1>Keşfet</h1><p>İlgini çeken kategoriyi seç.</p></section>${categoryBar()}<div class="feed">${list.length?list.map(shortCard).join(""):"<div class='panel'>Bu kategoride henüz video yok.</div>"}</div>`;observe()}
function observe(){document.querySelectorAll(".short").forEach(x=>{let o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){let id=e.target.querySelector(".act").getAttribute("onclick").match(/\d+/)[0];let v=videos.find(v=>v.id==id);if(v)v.views++;save()}}),{threshold:.7});o.observe(x)})}
function upload(){if(!current)return loginForm();$("#content").innerHTML=`<div class="panel form"><h1>Video Yükle</h1><p class="muted">Maksimum demo dosya boyutu: 100 MB. Gerçek sunucuya yükleme için backend/storage bağlantısı gerekir.</p><form onsubmit="addVideo(event)"><label>Video dosyası</label><input id="file" type="file" accept="video/mp4,video/webm,video/quicktime" required><div class="drop">9:16 dikey video önerilir.</div><label>Başlık</label><input id="title" maxlength="100" required><label>Kategori</label><select id="cat">${categories.slice(1).map(c=>`<option>${c}</option>`).join("")}</select><label>Açıklama</label><textarea id="desc" rows="4" maxlength="500"></textarea><p><input id="safe" type="checkbox" required> İçeriğin +18/pornografik olmadığını ve kurallara uygun olduğunu onaylıyorum.</p><button class="primary">Yükle ve Yayınla</button></form></div>`}
function addVideo(e){e.preventDefault();let f=$("#file").files[0];if(!f)return;if(f.size>100*1024*1024)return alert("Dosya 100 MB'dan büyük.");let v={id:Date.now(),title:$("#title").value,user:"@"+current.name,cat:$("#cat").value,likes:0,views:0,color:Math.floor(Math.random()*6)+1,file:f.name};videos.unshift(v);save();alert("Demo: video kaydedildi. Gerçek video depolaması için backend gerekir.");render("profile")}
function profile(){if(!current)return loginForm();let mine=videos.filter(v=>v.user==="@"+current.name);$("#content").innerHTML=`<div class="panel"><div class="profile-head"><div class="avatar">${current.name[0].toUpperCase()}</div><div><h1>${esc(current.name)}</h1><p class="muted">${esc(current.email)}</p><div class="stats"><span><b>${mine.length}</b> video</span><span><b>${mine.reduce((a,v)=>a+v.views,0)}</b> izlenme</span></div></div></div></div><h2>Videolarım</h2><div class="grid">${mine.map(v=>`<div class="card"><div class="thumb">▶</div><div class="card-body"><b>${esc(v.title)}</b><p class="muted">${v.cat} · ${v.views} izlenme</p></div></div>`).join("")||"<div class='panel'>Henüz video yüklemedin.</div>"}</div>`}
function admin(){if(!current||current.role!=="admin"){return openModal("<h2>Yetkisiz</h2><p>Admin paneline yalnızca yönetici hesabı erişebilir.</p>")}$("#content").innerHTML=`<h1>Admin Paneli</h1><div class="grid"><div class="panel"><h3>Kullanıcı</h3><strong>${users.length}</strong></div><div class="panel"><h3>Video</h3><strong>${videos.length}</strong></div><div class="panel"><h3>İzlenme</h3><strong>${videos.reduce((a,v)=>a+v.views,0)}</strong></div></div><div class="panel"><h2>Videolar</h2><table class="table"><tr><th>Başlık</th><th>Kullanıcı</th><th>Kategori</th><th>İşlem</th></tr>${videos.map(v=>`<tr><td>${esc(v.title)}</td><td>${esc(v.user)}</td><td><span class="badge">${v.cat}</span></td><td><button class="primary danger" onclick="deleteVideo(${v.id})">Sil</button></td></tr>`).join("")}</table></div>`}
function deleteVideo(id){if(confirm("Bu videoyu silmek istediğine emin misin?")){videos=videos.filter(v=>v.id!==id);save();admin()}}
function like(id){let v=videos.find(v=>v.id===id);v.likes++;save();render("home")}
function shareVideo(id){navigator.clipboard?.writeText(location.href+"#video-"+id);alert("Video bağlantısı kopyalandı.")}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
render();
